spring:
  application:
    name: edunova-backend
  
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/x?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:9986132559}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/edunova}

server:
  port: 8080

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 900000 # 15 minutes
  refresh-expiration: 604800000 # 7 days
